# Generated by Django 2.2.4 on 2019-08-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20190827_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='descricao',
            new_name='ano',
        ),
        migrations.AlterField(
            model_name='manga',
            name='autor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manga',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
